#!/usr/bin/python

import subprocess, sys, os, argparse
from pxr import *

def main(argumentList):
	parser = argparse.ArgumentParser()
	parser.add_argument("--verbose", "-v", action='store_true', help="Verbose mode.")
	parser.add_argument('files',nargs='*')
	args=parser.parse_args(argumentList)

	verboseOutput = args.verbose
	totalSuccess = True
	for filename in args.files:

		usdcheckerArgs = ["usdchecker", "--arkit", filename]
		if verboseOutput:
			print "Checking file", filename
			print "Running usdchecker"
			usdCheckerResult = (subprocess.call(usdcheckerArgs,) == 0)
		else: 
			FNULL = open(os.devnull, 'w')
			usdCheckerResult = (subprocess.call(usdcheckerArgs,stdout=FNULL,stderr=FNULL) == 0)

		from meshValidate import meshValidate
		meshSuccess = meshValidate(filename, verboseOutput)
		totalSuccess = totalSuccess and usdCheckerResult and meshSuccess
		if verboseOutput: 
			print
		else:
			print "usdARKitChecker:", ("[Pass]" if totalSuccess else "[Fail]"), filename

	if totalSuccess:
	    return 0
	else:
	    return 1

if __name__ == '__main__':
    argumentList = sys.argv[1:]
    sys.exit(main(argumentList))
